
class MOD_INFO:
    ID = '${MOD_ID}'
    NAME = '${MOD_NAME}'
    VERSION = '${MOD_VERSION}'
    VERSION_LONG = '${MOD_VERSION_LONG}'
    DEBUG = ${DEBUG}
    CONFIG_FILE = '${MOD_CONFIG_FILE}'
    SUPPORT_URL = '${SUPPORT_URL}'
